/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

import java.time.LocalDateTime;
import static javax.swing.JOptionPane.showMessageDialog;


public class ReServation2 extends javax.swing.JFrame {
    private javax.swing.JButton flag;
    private boolean reserve;
    private String customNum, name, callNum, roomNum, personNum;
    private SaveCustomer save;
    private DataShapeCustom data;
    private int selectRoomNum;
    private int[] checkIn = new int[4];
    private int[] checkOut = new int[4];
    private String sex;
    
    public ReServation2(javax.swing.JButton flag, int roomNum) {
        this.selectRoomNum=roomNum;
        this.flag=flag;
        initComponents();
        SearchCustomer search = new SearchCustomer();
        customNum = Integer.toString(search.SearchNextCustomNum());
        inputCliNum.setText(customNum);
        inputCliNum.setEnabled(false);
        inputRoomNum.setText(Integer.toString(selectRoomNum));
        inputRoomNum.setEnabled(false);
        checkIn[0]=2019;    checkIn[1]=1;   checkIn[2]=1;   checkIn[3]=11;
        checkOut[0]=2019;   checkOut[1]=1;  checkOut[2]=1;  checkOut[3]=11;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputName = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        inputCallNum = new javax.swing.JTextField();
        inputNumOfPerson = new javax.swing.JTextField();
        inputRoomNum = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputCliNum = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        CheckInYear = new javax.swing.JComboBox<>();
        CheckInDay = new javax.swing.JComboBox<>();
        CheckInHour = new javax.swing.JComboBox<>();
        CheckInMonth = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        CheckOutYear = new javax.swing.JComboBox<>();
        CheckOutDay = new javax.swing.JComboBox<>();
        CheckOutHour = new javax.swing.JComboBox<>();
        CheckOutMonth = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        ComboSex = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cancel.setText("취소");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jLabel1.setText("성함 :");

        jLabel2.setText("연락처 ('-' 제외) :");

        jLabel3.setText("인원 수 :");

        jLabel4.setText("방 번호 :");

        jLabel5.setText("@@@@@ 정보를 입력해 주세요 @@@@@");

        jLabel7.setText("고유번호 :");

        jLabel6.setText("체크인 시간");

        jLabel8.setText("체크아웃 시간");

        jPanel1.setForeground(new java.awt.Color(255, 204, 204));

        CheckInYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019년", "2020년", "2021년" }));
        CheckInYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInYearActionPerformed(evt);
            }
        });

        CheckInDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1일", "2일", "3일", "4일", "5일", "6일", "7일", "8일", "9일", "10일", "11일", "12일", "13일", "14일", "15일", "16일", "17일", "18일", "19일", "20일", "21일", "22일", "23일", "24일", "25일", "26일", "27일", "28일", "29일", "30일", "31일" }));
        CheckInDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInDayActionPerformed(evt);
            }
        });

        CheckInHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11시", "12시", "13시", "14시", "15시", "16시", "17시", "18시" }));
        CheckInHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInHourActionPerformed(evt);
            }
        });

        CheckInMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1월", "2월", "3월", "4월", "5월", "6월", "7월", "8월", "9월", "10월", "11월", "12월" }));
        CheckInMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInMonthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(CheckInYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckInMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(CheckInDay, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckInHour, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckInYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckInMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckInDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckInHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel3.setForeground(new java.awt.Color(255, 204, 204));

        CheckOutYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019년", "2020년", "2021년" }));
        CheckOutYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutYearActionPerformed(evt);
            }
        });

        CheckOutDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1일", "2일", "3일", "4일", "5일", "6일", "7일", "8일", "9일", "10일", "11일", "12일", "13일", "14일", "15일", "16일", "17일", "18일", "19일", "20일", "21일", "22일", "23일", "24일", "25일", "26일", "27일", "28일", "29일", "30일", "31일" }));
        CheckOutDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutDayActionPerformed(evt);
            }
        });

        CheckOutHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11시", "12시", "13시", "14시", "15시", "16시", "17시", "18시" }));
        CheckOutHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutHourActionPerformed(evt);
            }
        });

        CheckOutMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1월", "2월", "3월", "4월", "5월", "6월", "7월", "8월", "9월", "10월", "11월", "12월" }));
        CheckOutMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutMonthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(CheckOutDay, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CheckOutHour, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(CheckOutYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CheckOutMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckOutYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckOutMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckOutDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckOutHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jButton1.setText("저장");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ComboSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "남", "여" }));
        ComboSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboSexActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel6)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputRoomNum, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputCallNum, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputNumOfPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputCliNum, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ComboSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputCliNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(ComboSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputCallNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputRoomNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNumOfPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(jButton1))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed

        flag.setBackground(new java.awt.Color(153, 255, 204));
        
        showMessageDialog(null,"예약을 취소합니다.");
        reserve = false;
        dispose();

    }//GEN-LAST:event_cancelActionPerformed

    private void CheckInYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInYearActionPerformed
        // TODO add your handling code here:
        checkIn[0]=2019+CheckInYear.getSelectedIndex();
    }//GEN-LAST:event_CheckInYearActionPerformed

    private void CheckInMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInMonthActionPerformed
        // TODO add your handling code here:
        checkIn[1]=1+CheckInMonth.getSelectedIndex();
    }//GEN-LAST:event_CheckInMonthActionPerformed

    private void CheckInDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInDayActionPerformed
        // TODO add your handling code here:
        checkIn[2]=1+CheckInDay.getSelectedIndex();
    }//GEN-LAST:event_CheckInDayActionPerformed

    private void CheckInHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInHourActionPerformed
        // TODO add your handling code here:
        checkIn[3]=11+CheckInHour.getSelectedIndex();
    }//GEN-LAST:event_CheckInHourActionPerformed

    private void CheckOutYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutYearActionPerformed
        // TODO add your handling code here:
        checkOut[0]=2019+CheckOutYear.getSelectedIndex();
    }//GEN-LAST:event_CheckOutYearActionPerformed

    private void CheckOutMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutMonthActionPerformed
        // TODO add your handling code here:
        checkOut[1]=1+CheckOutMonth.getSelectedIndex();
    }//GEN-LAST:event_CheckOutMonthActionPerformed

    private void CheckOutDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutDayActionPerformed
        // TODO add your handling code here:
        checkOut[2]=1+CheckOutDay.getSelectedIndex();
    }//GEN-LAST:event_CheckOutDayActionPerformed

    private void CheckOutHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutHourActionPerformed
        // TODO add your handling code here:
        checkOut[3]=11+CheckOutHour.getSelectedIndex();
    }//GEN-LAST:event_CheckOutHourActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        name = inputName.getText();
        callNum = inputCallNum.getText();
        personNum = inputNumOfPerson.getText();
        LocalDateTime checkInDate;
        LocalDateTime checkOutDate;
        checkInDate = LocalDateTime.of(checkIn[0], checkIn[1], checkIn[2], checkIn[3], 0);
        checkOutDate = LocalDateTime.of(checkOut[0], checkOut[1], checkOut[2], checkOut[3], 0);
        DataShapeCheck check = new DataShapeCheck(checkInDate, null, checkOutDate, null);
        
        data = new DataShapeCustom(name, sex, callNum, Integer.parseInt(personNum), selectRoomNum, null, null, check, null);
        save = new SaveCustomer(data);
        flag.setBackground(new java.awt.Color(255, 153, 153));
        save.save();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ComboSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboSexActionPerformed
        // TODO add your handling code here:
        switch(ComboSex.getSelectedIndex()){
            case 0:
                sex="남";
                break;
            case 1:
                sex="여";
                break;
            default:
                break;
        }
    }//GEN-LAST:event_ComboSexActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CheckInDay;
    private javax.swing.JComboBox<String> CheckInHour;
    private javax.swing.JComboBox<String> CheckInMonth;
    private javax.swing.JComboBox<String> CheckInYear;
    private javax.swing.JComboBox<String> CheckOutDay;
    private javax.swing.JComboBox<String> CheckOutHour;
    private javax.swing.JComboBox<String> CheckOutMonth;
    private javax.swing.JComboBox<String> CheckOutYear;
    private javax.swing.JComboBox<String> ComboSex;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField inputCallNum;
    private javax.swing.JTextField inputCliNum;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputNumOfPerson;
    private javax.swing.JTextField inputRoomNum;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
